name: 'Hangman'

on:
  issues:
    types: [opened]

jobs:
  move:
    runs-on: ubuntu-latest
    if: startsWith(github.event.issue.title, 'hangman|')
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm install
      - run: node index.js ${{ github.event.issue.title }}
